name: pic_reminder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.6.2
  image_picker: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.20.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  path: ^1.9.0
  uuid: ^4.5.1
  timezone: ^0.10.0
  flutter_local_notifications: ^19.0.0
  flutter_timezone: ^4.1.0
  photo_manager: ^3.1.1

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/reminder_logo.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/reminder_logo.png
